-- Création de toutes les tables utiles pour le site

-- CREATE DATABASE terminologio COLLATE utf8_general_ci;
-- CREATE DATABASE projet COLLATE utf8_general_ci;

-- USE terminologio;
USE projet;

CREATE TABLE MEMBER (
    IDMEM INT AUTO_INCREMENT,
    FIRSTNAMEMEM VARCHAR(255) NOT NULL,
    LASTNAMEMEM VARCHAR(255) NOT NULL,
    MAILMEM VARCHAR(255) NOT NULL,
    PSEUDOMEM VARCHAR(255) NOT NULL,
    MDPMEM VARCHAR(255) NOT NULL,
    CONSTRAINT PKMEMBER
    PRIMARY KEY (IDMEM)
)ENGINE = InnoDB;

CREATE TABLE LANG (
    IDLANG INT AUTO_INCREMENT,
    NAMELANG VARCHAR(50) NOT NULL,
    CODELANG VARCHAR(2) NOT NULL,
    COMPLANG VARCHAR(255) NOT NULL,
    -- IMGLANG VARCHAR(50) NOT NULL,
    CONSTRAINT PKLANG
    PRIMARY KEY(IDLANG)
)ENGINE = InnoDB;

CREATE TABLE PARAMETER (
    MEMIDPARAM INT NOT NULL,
    ISDARKMODEPARAM BOOLEAN NOT NULL DEFAULT FALSE,
    COLORPARAM VARCHAR(10) NOT NULL DEFAULT "#000000",
    -- NBCONCEPTDISPLAYPARAM INT NOT NULL DEFAULT 5,
    -- LANGIDPARAM INT NOT NULL,
    CONSTRAINT FKPARAMETERSMEMIDMEMBER
    FOREIGN KEY (MEMIDPARAM)
    REFERENCES MEMBER(IDMEM)
    -- CONSTRAINT FKPARAMETERIDLANG
    -- FOREIGN KEY (LANGIDPARAM)
    -- REFERENCES LANG(IDLANG)
)ENGINE = InnoDB;

CREATE TABLE USES (
    MEMBERUSES INT NOT NULL,
    LANGUSES INT NOT NULL,
    CONSTRAINT FKUSESMEMBER
    FOREIGN KEY (MEMBERUSES)
    REFERENCES MEMBER(IDMEM),
    CONSTRAINT FKUSESLANG
    FOREIGN KEY (LANGUSES)
    REFERENCES LANG(IDLANG),
    CONSTRAINT PKUSES
    PRIMARY KEY (MEMBERUSES, LANGUSES)
)ENGINE = InnoDB;

CREATE TABLE CATEGORIE (
    IDCATEGORIE INT NOT NULL AUTO_INCREMENT,
    NAMECATEGORIE VARCHAR(255) NOT NULL,
    CONSTRAINT PKCATEGORIE
    PRIMARY KEY (IDCATEGORIE)
)ENGINE = InnoDB;

CREATE TABLE CONCEPT (
    IDCON INT NOT NULL AUTO_INCREMENT,
    TITLECON VARCHAR(255) NOT NULL,
    REPRESENTATIONCON VARCHAR(255) NOT NULL,
    DEFAULTLANGIDCON INT NOT NULL,
    AUTHORCON INT NOT NULL,
    CONSTRAINT PKCONCEPT
    PRIMARY KEY(IDCON),
    CONSTRAINT FKCONCEPTLANGIDLANG
    FOREIGN KEY (DEFAULTLANGIDCON)
    REFERENCES LANG(IDLANG),
    CONSTRAINT FKCONCEPTAUTHORMEMBER
    FOREIGN KEY (AUTHORCON)
    REFERENCES MEMBER(IDMEM)
)ENGINE = InnoDB;

CREATE TABLE COMING_FROM (
    CF_CATEGORIE INT NOT NULL,
    CF_CONCEPT INT NOT NULL,
    CONSTRAINT FKCFCATEGORIE
    FOREIGN KEY (CF_CATEGORIE)
    REFERENCES CATEGORIE(IDCATEGORIE),
    CONSTRAINT FKCFCON
    FOREIGN KEY (CF_CONCEPT)
    REFERENCES CONCEPT(IDCON),
    CONSTRAINT PKCF
    PRIMARY KEY (CF_CATEGORIE, CF_CONCEPT)
)ENGINE = InnoDB;

CREATE TABLE COMPONENT (
    IDCOMPONENT INT NOT NULL AUTO_INCREMENT,
    POSXCOMP INT NOT NULL,
    POSYCOMP INT NOT NULL,
    TERMINOLOGYCOMP VARCHAR(255) NOT NULL,
    DEFINEDTERM INT NOT NULL,
    CONSTRAINT PKCOMPONENT
    PRIMARY KEY (IDCOMPONENT),
    CONSTRAINT FKCOMPONENTDEFINEDCONCEPT
    FOREIGN KEY (DEFINEDTERM)
    REFERENCES CONCEPT(IDCON)
)ENGINE = InnoDB;

CREATE TABLE TRANSLATE (
    LANGIDTRANS INT NOT NULL,
    COMPONENTIDTRANS INT NOT NULL,
    TRANSLATETERM VARCHAR(255) NOT NULL,
    CONSTRAINT FKTRANSLATELANG
    FOREIGN KEY (LANGIDTRANS)
    REFERENCES LANG(IDLANG),
    CONSTRAINT FKTRANSCOMPONENT
    FOREIGN KEY (COMPONENTIDTRANS)
    REFERENCES COMPONENT(IDCOMPONENT),
    CONSTRAINT PKTRANSLATE
    PRIMARY KEY (LANGIDTRANS, COMPONENTIDTRANS)
)ENGINE = InnoDB;

CREATE TABLE MARKED (
    CONCEPTIDMARK INT NOT NULL,
    MEMBERIDMARK INT NOT NULL,
    CONSTRAINT FKMARKEDCONCEPT
    FOREIGN KEY (CONCEPTIDMARK)
    REFERENCES CONCEPT(IDCON),
    CONSTRAINT FKMARKEDMEMBER
    FOREIGN KEY (MEMBERIDMARK)
    REFERENCES MEMBER(IDMEM),
    CONSTRAINT PKMARKED
    PRIMARY KEY (CONCEPTIDMARK, MEMBERIDMARK)
)ENGINE = InnoDB;


ALTER TABLE MEMBER COLLATE utf8_general_ci;
ALTER TABLE LANG COLLATE utf8_general_ci;
ALTER TABLE PARAMETER COLLATE utf8_general_ci;
ALTER TABLE USES COLLATE utf8_general_ci;
ALTER TABLE CATEGORIE COLLATE utf8_general_ci;
ALTER TABLE CONCEPT COLLATE utf8_general_ci;
ALTER TABLE COMING_FROM COLLATE utf8_general_ci;
ALTER TABLE COMPONENT COLLATE utf8_general_ci;
ALTER TABLE TRANSLATE COLLATE utf8_general_ci;
ALTER TABLE MARKED COLLATE utf8_general_ci;
